config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :boards, only: [:new, :create, :edit, :update, :destroy]
  root to: 'home#index'
  get "boards", to: "home#index"
  # resources :boards do
  #   resources :tasks
  # end
  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy

    validates :name, presence: true, length: { minimum: 3, maximum: 20 }
    validates :description, length: { minimum: 20, maximum: 500 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :content, presence: true, length: { maximum: 500 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :board
  has_one_attached :eyecatch
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 10 }
  validates :content, presence: true, length: { minimum: 20, maximum: 300 }
  validates :deadline, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  def name
    email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_board, only: [:edit, :update, :destroy]
    before_action :authorize_user!, only: [:edit, :update, :destroy]

    def new
        @board = current_user.boards.build
    end

    def edit
        # ここで @board は set_board メソッドによってセットされる
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to root_path, notice: 'ボードを作成しました。'
        else
            flash.now[:error] = '作成できませんでした'
            render :new
        end
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
          redirect_to boards_path, notice: "ボードを更新しました"
        else
          flash.now[:error] = '更新できませんでした'
          render :edit
        end
    end
    
    def destroy
        @board.destroy
        redirect_to boards_path, notice: "ボードを削除しました"
    end

    private

    def set_board
        @board = Board.find(params[:id])
    end
    
    def authorize_user!
        redirect_to boards_path, alert: "権限がありません" unless @board.user == current_user
    end

    def board_params
        params.require(:board).permit(
            :name,
            :description,
            :avatar
        )
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_task
    before_action :authenticate_user!
  
    def new
      @comment = Comment.new
    end
  
    def create
      @comment = @task.comments.build(comment_params)
      @comment.user = current_user
      if @comment.save
        redirect_to board_task_path(@task.board, @task), notice: 'コメントを追加しました。'
      else
        flash.now[:error] = 'コメントを追加できませんでした。'
        render :new
      end
    end
  
    private
  
    def set_task
      @task = Task.find(params[:task_id])
    end
  
    def comment_params
      params.require(:comment).permit(:content)
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

    def index
      @boards = Board.includes(:user).all
    end
  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_board
    before_action :set_task, only: [:edit, :update, :destroy, :show]

    def index
      @tasks = @board.tasks
    end
  
    def new
      @task = @board.tasks.build
    end
  
    def create
      @task = @board.tasks.build(task_params)
      @task.user = current_user
      if @task.save
        redirect_to board_tasks_path(@board), notice: "タスクを作成しました"
      else
        flash.now[:error] = '作成できませんでした'
        render :new
      end
    end

    def show
    end

    def edit
    end
  
    def update
      if @task.update(task_params)
        redirect_to board_tasks_path(@board), notice: "タスクを更新しました"
      else
        flash.now[:error] = '更新できませんでした'
        render :edit
      end
    end
  
    def destroy
      @task.destroy
      redirect_to board_tasks_path(@board), notice: "タスクを削除しました"
    end
  
    private
  
    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_task
      @task = @board.tasks.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to board_tasks_path(@board), alert: "指定されたタスクが見つかりません。"
    end
  
    def task_params
      params.require(:task).permit(:title, :content, :deadline, :eyecatch)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
.container
    %h2.header_pageTitle Edit Board
    .new-board-form
        = form_with(model: @board, local: true) do |f|
            %div.board_field
                = f.label :name, 'Name'
                = f.text_field :name
            %div.board_field
                = f.label :description, 'Description'
                = f.text_area :description, class: "board-description"
            .actions
                = f.submit "Submit", class: "submit-btn"

app/views/boards/new.html.haml
.container
    %h2.header_pageTitle New Board
    .new-board-form
        = form_with(model: @board, url: boards_path, local: true) do |f|
            %div.board_field
                = f.label :name, 'Name'
                %br/
                = f.text_field :name
            %div.board_field
                = f.label :description, 'Description'
                %br/
                = f.text_area :description, class: "board-description"
            .actions
                = f.submit "Submit", class: "submit-btn"

app/views/comments/new.html.haml
.container
  %h2 New Comment
  .new-board-form
    = form_with model: [@task, @comment], url: board_task_comments_path(@task.board, @task), local: true do |f|
      .back-link
        = link_to "×", board_task_path(@task.board, @task)
      .field
        = f.text_area :content, class: "board-description"
      .actions
        = f.submit "Submit", class: "submit-btn"

app/views/home/index.html.haml
.board_container
    %h2.header_pageTitle All Boards
    %div.board_content
        %div.board_boxes
            - @boards.each do |board|
                %div.board_box
                    %div.board_box-top
                        = link_to board_tasks_path(board), class: "board_link" do
                            %span.board_name= board.name

                        - if board.user == current_user
                            .menu-container
                                %button.menu-button{ tabindex: "0" }
                                    = image_tag 'actions.svg', class: 'dropbtn'
                                .menu-content
                                    = link_to 'Edit', edit_board_path(board), class: "menu-item"
                                    = link_to 'Delete', board_path(board), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "menu-item"

                    %div
                        %p.board_description= board.description
                    .field
                        %p
                            - if board.user&.avatar&.attached?
                                = image_tag board.user.avatar, alt: "Board Creator Avatar", class: "user-avatar"
                            - else
                                = image_tag "default-avatar.png", alt: "Default Avatar", class: "user-avatar"

    .board_add
        = link_to "+ Add new board", new_board_path, class: "add-board-button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ "http-equiv" => "Content-Type", content: "text/html; charset=UTF-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    %link{:href => "https://fonts.googleapis.com", :rel => "preconnect"}/
    %link{:crossorigin => "", :href => "https://fonts.gstatic.com", :rel => "preconnect"}/
    %link{:href => "https://fonts.googleapis.com/css2?family=Sen:wght@400..800&display=swap", :rel => "stylesheet"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.header 
      %h2 Boards
      - if user_signed_in?
        .avatar-container
          - if current_user.avatar.attached?
            = image_tag current_user.avatar, alt: "User Avatar", class: "user-avatar"
          - else
            = image_tag "default-avatar.png", alt: "Default Avatar", class: "user-avatar"
          .dropdown-menu
            %p= current_user.email.split('@').first
            = link_to "編集", edit_user_registration_path
            = link_to "ログアウト", destroy_user_session_path, data: { method: 'delete' }
      - else
        .header_buttons
          = link_to "ログイン", new_user_session_path
          = link_to "新規登録", new_user_registration_path

    .message-wrap
      %p.notice= notice
      %p.alert= alert
    = yield

app/views/tasks/edit.html.haml
.container
  %h2 Edit Task
  .new-board-form
    = form_with model: [@board, @task], local: true do |f|
      %div.board_field
        = f.label :title, "Name"
        %br/
        = f.text_field :title
      %div.board_field
        = f.label :content, "Description"
        %br/
        = f.text_area :content, class: "board-description"
      %div.board_field
        = f.label :deadline, "Deadline"
        %br/
        = f.datetime_field :deadline
      %div.board_field
        = f.label :eyecatch, "アイキャッチ"
        %br/
        = f.file_field :eyecatch
      .actions
        = f.submit "Submit", class: "submit-btn"

app/views/tasks/index.html.haml
.container
  %h2= "#{@board.name}"
  %div.board_content
    %div.board_boxes
      - @tasks.each do |task|
        = link_to board_task_path(@board, task), class: "task-link" do
          %div.board_box
            - if task.eyecatch.attached?
              .task_eyecatch
                = image_tag task.eyecatch
            %span.board_name= task.title
            %div
              %p.task_description= truncate(task.content, length: 92, omission: '...')
            %div
              - if task.deadline.present?
                %p.task_deadline= "Deadline: #{task.deadline.strftime('%Y-%m-%d %H:%M')}"
            
            .comment-users
              - task.comments.includes(:user).map(&:user).uniq.each do |user|
                - if user.avatar.attached?
                  = image_tag user.avatar, class: "comment-user-avatar", alt: "#{user.email.split('@').first}'s avatar"
                - else
                  = image_tag "default-avatar.png", class: "comment-user-avatar", alt: "Default avatar"

            .comment-info
              %span.comment-count= task.comments.count
              = image_tag "comment-count.png", alt: "Comment Count", class: "comment-icon"
  
  .board_add
    = link_to "+ Add new card", new_board_task_path(@board), class: "add-task-button"

app/views/tasks/new.html.haml
.container
  %h2.header_pageTitle New Card
  .new-board-form
    = form_with(model: @task, url: board_tasks_path(@board), local: true, html: { multipart: true }) do |f|
      %div.board_field
        = f.label :title, "Name"
        %br/
        = f.text_field :title
      %div.board_field
        = f.label :content, "Description"
        %br/
        = f.text_area :content, class: "board-description"
      %div.board_field
        = f.label :deadline, "Deadline"
        %br/
        = f.datetime_field :deadline
      %div.board_field
        = f.label :eyecatch, "アイキャッチ"
        %br/
        = f.file_field :eyecatch
      .actions
        = f.submit "Submit", class: "submit-btn"

app/views/tasks/show.html.haml
.container
  %div.task-header
    %h2.header_pageTitle= truncate(@task.title, length: 20, omission: '...')
    .menu-container
      %button.menu-button{ tabindex: "0" }
        = image_tag 'actions.svg', class: 'dropbtn'
      .menu-content
        = link_to 'Edit', edit_board_task_path(@board, @task), class: "menu-item"
        = link_to 'Delete', board_task_path(@board, @task), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "menu-item"

  - if @task.eyecatch.attached?
    %div.task_eyecatch-show
      = image_tag @task.eyecatch

  %div.task_description-show
    %p= @task.content

  .comments-section
    %h2.comment_title Comment
    - if @task.comments.any?
      - @task.comments.each do |comment|
        .comment_box
          .comment-header
            - if comment.user.avatar.attached?
              = image_tag comment.user.avatar, class: "comment-avatar"
            - else
              = image_tag "default-avatar.png", class: "comment-avatar"
          .comment-content
            %p= truncate(comment.content, length: 120, omission: '...')
    - else
      %p まだコメントはありません。

    .comment_add
      = link_to "+ Add new comment", new_board_task_comment_path(@task.board, @task)